MAA1999/M9A

assets/resource/pipeline/wilderness.json

fix: 修复卡信赖问题

---

source/cli/main.cpp

fix: 修复不能正确启动B服的问题

---

assets/resource/pipeline/activity/ThePrisonerintheCave.json

fix: 优化刷取`证明启示V`关卡的操作稳健性

---

assets/resource/base/pipeline/activity/outsidededuction.json

fix：肉鸽循环问题

---

.gitignore
assets/resource/base/pipeline/activity/StagePromotion.json

进入均衡模式后无法进入战斗，所以在均衡模式之后添加了next；有时直接跳过剧情后，会直接进入均衡模式，在StagePromotion_Confirm加入均衡模式。
Fixes #139

fix: 修复自动推图相关 bug

---

assets/interface.json
assets/resource/base/pipeline/eat_candy.json

https://github.com/MaaXYZ/M9A/issues/138 加入识别关卡中文名

fix：有时候关卡识别失败

---

install.py

Revert "新增interface显示项目名称和版本号"

---

assets/resource/base/pipeline/activity/outsidededuction.json

fix：肉鸽有的时候不选人

---

assets/interface.json
assets/resource/base/pipeline/awards.json
assets/resource/base/pipeline/wilderness.json

feat: 新增魔精收菜可选，默认收取。
fix: 修复领取奖励的问题。
GUI暂不可用

feat: 新增魔精收菜可选。

---

assets/interface.json
assets/resource/base/pipeline/awards.json

fix: 修复卡点唱机，MFA控制器锁定为ADB

---

assets/interface.json

https://github.com/MaaXYZ/M9A/issues/226
适配MFA检查资源更新。

feat: interface新增项目名称和项目链接

---

.github/ISSUE_TEMPLATE/cn-bug-report.yaml
.github/ISSUE_TEMPLATE/cn-feature-request.yaml
.github/ISSUE_TEMPLATE/cn-others.yaml
.github/ISSUE_TEMPLATE/en-bug-report.yaml
.github/ISSUE_TEMPLATE/en-feature-request.yaml
.github/ISSUE_TEMPLATE/en-others.yaml

Reference from https://github.com/MaaAssistantArknights/MaaAssistantArknights

docs: Issue Template

---

assets/resource/base/pipeline/activity/outside_deduction_rapid.json

fix https://github.com/MaaXYZ/M9A/issues/322

fix: 肉鸽速刷选择选项后卡住

---

assets/interface.json
assets/resource/base/pipeline/awards.json

fix https://github.com/MaaXYZ/M9A/issues/283

feat: 完成周任务后获取显影罐

---

assets/resource/base/pipeline/startup.json
assets/resource/base/pipeline/wilderness.json

fix https://github.com/MaaXYZ/M9A/issues/273

refactor: 荒原收菜改为进入古厅后进行

---

assets/interface.json

revert: "feat: 支持国际服PC端"

---

assets/interface.json

fix https://github.com/MaaXYZ/M9A/issues/351

fix: 修复外服无法正常进入东区黎明的问题

---

assets/resource/base/pipeline/awards.json

fix https://github.com/MaaXYZ/M9A/issues/360

fix: 修复卡在购买典藏吼吼光碟界面的问题

---

assets/resource/base/pipeline/activity/outside_deduction.json

fix https://github.com/MaaXYZ/M9A/issues/361

fix: 自动取消挂载第三个资料片

---

assets/interface.json

chore: 更新主线推荐关卡v2.6

---

.github/workflows/mirrorchyan.yml

ci: upload full package for mirrorchyan

---

agent/custom/action/__init__.py
agent/custom/action/combat.py
assets/interface.json
assets/resource/base/pipeline/combat.json
docs/zh_cn/develop/项目重构.md

refactor: 作战关卡 #499

---

assets/resource/base/pipeline/anecdote.json
assets/resource/global_jp/pipeline/anecdote.json

chore: 国服更新轶事。外服不变

---

agent/main.py

[Maa Pipeline Support](https://marketplace.visualstudio.com/items?itemName=nekosu.maa-support) vsc插件在当前目录中已经存在`.venv`时会直接安装依赖，但我们无法保证这个`.venv`环境中是否有pip。
比如使用[uv](https://docs.astral.sh/uv/)作为包管理器并运行`uv venv`创建的`.venv`环境中，就默认没有pip。

chore: 在安装依赖前检查当前环境中是否有pip
